name = "aafu"
license = "MIT"
licenselink = "https://github.com/darshanbaral/aafu/blob/master/LICENSE"
description = "Portfolio and blog theme with search and dark/light theme."
homepage = "https://github.com/darshanbaral/aafu"
demosite = "https://aafu.darshanbaral.com/"
tags = ["portfolio", "accordion", "resume", "blog", "tailwind"]
features = ["responsive", "dark", "clean"]
min_version = "0.152.2"
theme_version = "2025.11.30"

[author]
  name = "Darshan Baral"
  homepage = "https://www.darshanbaral.com/"
